# ai_engine/graph/state.py

from typing import TypedDict, Optional, List, Annotated
import operator


class TripProfile(TypedDict):
    """
    Per-trip travel profile.

    Replaces the old user-level BehavioralProfile. Each trip has its own
    profile built from conversation context — a user can be budget-conscious
    for Istanbul but luxury-oriented for Thailand.

    Stored in the trip_profiles table (1:1 with trips).
    """
    profile_id: Optional[str]
    trip_id: Optional[str]

    # ── Core Preferences ──────────────────────────────────────────
    budget_level: Optional[str]        # "budget" | "moderate" | "luxury"
    travel_style: Optional[str]        # "romantic" | "adventure" | "family" | "solo" | "cultural" | "relaxation"
    pace: Optional[str]                # "relaxed" | "moderate" | "packed"

    # ── Interest & Preference Lists ───────────────────────────────
    interests: List[str]               # e.g. ["history", "food", "art"]
    food_preferences: List[str]        # e.g. ["local cuisine", "street food"]
    accommodation_preferences: List[str]  # e.g. ["boutique hotel", "airbnb"]

    # ── Dimension Scores (0.0 – 1.0) ─────────────────────────────
    luxury_score: Optional[float]
    culture_score: Optional[float]
    adventure_score: Optional[float]
    shopping_score: Optional[float]
    family_score: Optional[float]

    # ── Metadata ─────────────────────────────────────────────────
    confidence: Optional[float]        # 0.0-1.0 how confident we are in the profile
    generated_at: Optional[str]        # ISO-8601 timestamp of profile creation
    updated_at: Optional[str]          # ISO-8601 timestamp of last update


class TripState(TypedDict):
    """
    Central state object shared across all agents in the LangGraph pipeline.

    Each agent reads from and writes to this structure. It holds both input data,
    intermediate results, and final outputs for itinerary generation.
    """

    # ── Request Data ────────────────────────────────────────────────
    user_id: str
    # Identifies the user making the request

    user_message: str
    # Raw input from the user (e.g., "Plan me a 5-day trip to Paris")

    conversation_context: Optional[str]
    # Full conversation history summary for context-aware agents
    # (preference, planning) — built from ConversationState.history

    token: Optional[str]
    # Firebase auth token for authenticated API calls (e.g. profile loading)

    trip_id: Optional[str]
    # Trip identifier for loading per-trip profile


    # ── Loaded Profile (per-trip) ───────────────────────────────────
    profile: Optional[TripProfile]


    # ── Preference Extraction ─────────────────────────────────────
    extracted_preferences: Optional[dict]
    # Structured preferences extracted by Preference Agent:
    # {budget_level, travel_style, walking_tolerance, food_preferences,
    #  accommodation_style, nightlife, interests_from_conversation}

    # ── Retrieval Pipeline ────────────────────────────────────────
    filtered_places: Optional[List[dict]]
    # Places after SQL/DB filtering (Stage 1 of retrieval)

    candidate_places: Optional[List[dict]]
    # Final candidate set after ranking + diversity (sent to planner)

    # ── Itinerary Pipeline Outputs ──────────────────────────────────
    draft_itinerary: Optional[dict]
    # Initial itinerary generated by the planning agent (unoptimized)

    optimized_itinerary: Optional[dict]
    # Improved version after applying optimization (timing, routing, etc.)

    is_valid: Optional[bool]
    # Result of validation step (True if itinerary meets constraints)

    validation: Optional[dict]
    # Full validation verdict (score, issues, warnings, suggestions)

    planning_attempts: Optional[int]
    # How many times the planner has run (used to cap plan->validate retries)


    # ── Control Flow State ──────────────────────────────────────────
    next_agent: Optional[str]
    # Indicates which agent should run next in the pipeline

    error: Optional[str]
    # Stores error message if any step fails

    # Add these keys to the TripState TypedDict in ai/graph/state.py
    intent_type:         str           # "plan_trip" | "needs_clarification" | "general_chat"
    destination_city:    Optional[str]
    destination_country: Optional[str]
    duration_days:       Optional[int]
    travel_dates:        Optional[str]
    special_requests:    Optional[str]
    group_size:          Optional[int]
    traveler_group_type: Optional[str]
    missing_fields:      list[str]     # fields the user hasn't provided yet

    # ── Agent Trace / Debugging ─────────────────────────────────────
    agent_messages: Annotated[List[str], operator.add]
    """
    Stores messages produced by agents during execution.

    The Annotated[List[str], operator.add] ensures that new messages
    are appended instead of replacing existing ones. This allows full
    traceability of agent decisions and is useful for debugging and logging.
    """