# ai/graph/state.py

from typing import TypedDict, Optional, List, Annotated
import operator


class BehavioralProfile(TypedDict):
    """
    Represents the user's long-term profile data.

    This structure mirrors the UserProfile table in the backend database
    and is loaded once per request. It is used by the AI system to personalize
    itinerary generation and decision-making.
    """
    user_id: str  # Unique identifier linking this profile to a user

    # ── Demographics ────────────────────────────────────────────────
    age: Optional[int]              # User age (may be missing if not provided)
    sex: Optional[str]              # User gender (free text or predefined values)
    travel_companion: Optional[str] # Type of travel group (e.g., "solo", "partner", "family", "friends")

    location: Optional[str]         # User's home location (used for personalization)

    # ── Preference Sliders (0–100 scale from quiz) ──────────────────
    # These represent behavioral tendencies derived from onboarding quiz

    adventure_relaxing: Optional[int]
    # 0 = prefers relaxing activities, 100 = prefers adventurous activities

    nature_culture: Optional[int]
    # 0 = prefers nature, 100 = prefers cultural experiences

    popular_local: Optional[int]
    # 0 = prefers popular/tourist places, 100 = prefers local/hidden spots

    budget_level: Optional[int]
    # 0 = budget-conscious, 100 = luxury-oriented

    early_night: Optional[int]
    # 0 = early sleeper, 100 = prefers nightlife

    independent_social: Optional[int]
    # 0 = prefers independent activities, 100 = prefers social/group activities

    # ── Multi-select Preferences ────────────────────────────────────
    # Lists collected from user selections during onboarding

    accommodation_styles: List[str] # Example: ["hotel", "hostel", "airbnb"]

    dining_preferences: List[str]   # Example: ["street food", "fine dining"]

    interests: List[str]
    # Core interests used to filter and rank places

    traveler_types: List[str]
    # Higher-level labels (e.g., "adventurer", "culture seeker")

    # ── AI-generated Persona ────────────────────────────────────────
    # These fields are derived from the profile to guide tone and recommendations

    persona_name: Optional[str]
    # Short label representing the user (e.g., "The Budget Explorer")

    persona_bio: Optional[str]
    # Description of the user's travel style and preferences

    suggested_questions: Optional[List[str]]
    # Follow-up questions the system may ask to refine trip planning

    # ── Completion Flag ─────────────────────────────────────────────
    quiz_completed: bool
    # Indicates whether the onboarding quiz was fully completed


class TripState(TypedDict):
    """
    Central state object shared across all agents in the LangGraph pipeline.

    Each agent reads from and writes to this structure. It holds both input data,
    intermediate results, and final outputs for itinerary generation.
    """

    # ── Request Data ────────────────────────────────────────────────
    user_id: str
    # Identifies the user making the request

    user_message: str
    # Raw input from the user (e.g., "Plan me a 5-day trip to Paris")

    token: Optional[str]
    # Firebase auth token for authenticated API calls (e.g. profile loading)


    # ── Loaded Profile ──────────────────────────────────────────────
    profile: Optional[BehavioralProfile]
    # User profile loaded from backend; may be None if not available


    # ── Itinerary Pipeline Outputs ──────────────────────────────────
    draft_itinerary: Optional[dict]
    # Initial itinerary generated by the planning agent (unoptimized)

    optimized_itinerary: Optional[dict]
    # Improved version after applying optimization (timing, routing, etc.)

    is_valid: Optional[bool]
    # Result of validation step (True if itinerary meets constraints)

    validation: Optional[dict]
    # Full validation verdict (score, issues, warnings, suggestions)

    planning_attempts: Optional[int]
    # How many times the planner has run (used to cap plan->validate retries)


    # ── Control Flow State ──────────────────────────────────────────
    next_agent: Optional[str]
    # Indicates which agent should run next in the pipeline

    error: Optional[str]
    # Stores error message if any step fails

    # Add these keys to the TripState TypedDict in ai/graph/state.py
    intent_type:         str           # "plan_trip" | "needs_clarification" | "general_chat"
    destination_city:    Optional[str]
    destination_country: Optional[str]
    duration_days:       Optional[int]
    travel_dates:        Optional[str]
    special_requests:    Optional[str]
    group_size:          Optional[int]
    missing_fields:      list[str]     # fields the user hasn't provided yet

    # ── Agent Trace / Debugging ─────────────────────────────────────
    agent_messages: Annotated[List[str], operator.add]
    """
    Stores messages produced by agents during execution.

    The Annotated[List[str], operator.add] ensures that new messages
    are appended instead of replacing existing ones. This allows full
    traceability of agent decisions and is useful for debugging and logging.
    """