import copy
from ai_engine.graph.state import TripState
from ai_engine.tools.routing_tool import order_stops_by_proximity, get_reorder_indices, improve_order_2opt, compute_day_matrix, WALK_THRESHOLD_KM
from ai_engine.tools.haversine import haversine


async def run_optimization_agent(state: TripState) -> TripState:
    """
    Optimization Agent

    Purpose:
    - Takes the draft itinerary generated by planning agent.
    - Creates a deep copy to avoid modifying the original draft itinerary.
    - Reorders stops within each day based on geographic proximity.
    - Computes travel times via OSRM with mixed modes:
      walking for nearby pairs (< 2 km), driving for the rest.
    - Tags each stop with a ``transport_mode`` ("walking" | "driving")
      so the front end can display the right icon.
    - Stores the optimized result in state["optimized_itinerary"].

    Input:
    - state: Shared TripState object containing the draft itinerary.

    Output:
    - Updated state with an optimized itinerary.
    """

    # Retrieve the draft itinerary produced by previous planning agents.
    draft = state.get("draft_itinerary")

    # Exit early if:
    # 1. No draft itinerary exists.
    # 2. A previous agent has already recorded an error.
    if not draft or state.get("error"):
        return state

    # Create a deep copy so modifications do not affect the original draft.
    optimized = copy.deepcopy(draft)

    # Iterate through each day in the itinerary.
    for day in optimized.get("days", []):

        # Retrieve all stops planned for the current day.
        stops = day.get("stops", [])

        # Optimization only makes sense when there are at least two stops.
        if len(stops) > 1:

            # --- Step 1: Compute the travel-time matrix first ---
            # We need real travel times BEFORE reordering so the
            # reordering algorithm can use them instead of Euclidean.
            matrix = await compute_day_matrix(stops)

            # --- Step 2: Reorder using actual travel times ---
            # Nearest-neighbor on the matrix produces far better routes
            # than Euclidean because it accounts for real roads.
            nn_idx = get_reorder_indices(stops, matrix)

            # --- Step 2b: Improve with 2-opt local search ---
            # 2-opt tries reversing segments to find shorter routes.
            # O(n²) per iteration, typically converges in < 10 passes.
            reorder_idx = improve_order_2opt(nn_idx, matrix)
            reordered_stops = [stops[i] for i in reorder_idx]

            # --- Step 3: Annotate stops with travel times and mode ---
            # Use reorder_idx to look up travel times from the original
            # matrix without fragile id()-based remapping.
            for i in range(len(reordered_stops) - 1):
                oi = reorder_idx[i]       # original index of current stop
                oj = reorder_idx[i + 1]   # original index of next stop
                dist_km = haversine(
                    reordered_stops[i]["lat"], reordered_stops[i]["lon"],
                    reordered_stops[i + 1]["lat"], reordered_stops[i + 1]["lon"],
                )
                mode = "walking" if dist_km <= WALK_THRESHOLD_KM else "driving"
                reordered_stops[i]["travel_time_to_next_minutes"] = matrix[oi][oj]
                reordered_stops[i]["transport_mode"] = mode

            day["stops"] = reordered_stops

        # Sum travel times for all stops in this day.
        total_travel = sum(
            s.get("travel_time_to_next_minutes", 0) for s in day.get("stops", [])
        )
        day["total_travel_time_minutes"] = round(total_travel, 1)

    # Save the optimized itinerary into the shared state.
    state["optimized_itinerary"] = optimized

    return state