import copy
from ai_engine.graph.state import TripState
from ai_engine.tools.routing_tool import order_stops_by_proximity, get_travel_time_minutes


async def run_optimization_agent(state: TripState) -> TripState:
    """
    Optimization Agent

    Purpose:
    - Takes the draft itinerary generated by planning agent.
    - Creates a deep copy to avoid modifying the original draft itinerary.
    - Reorders stops within each day based on geographic proximity
      (currently using a placeholder/mock implementation, but designed
      for future routing optimization).
    - Calculates travel time between consecutive stops.
    - Stores the optimized result in state["optimized_itinerary"].

    Input:
    - state: Shared TripState object containing the draft itinerary.

    Output:
    - Updated state with an optimized itinerary.
    """

    # Retrieve the draft itinerary produced by previous planning agents.
    draft = state.get("draft_itinerary")

    # Exit early if:
    # 1. No draft itinerary exists.
    # 2. A previous agent has already recorded an error.
    if not draft or state.get("error"):
        return state

    # Create a deep copy so modifications do not affect the original draft.
    # Deep copy is important because the itinerary contains nested objects
    # such as days and stops.
    optimized = copy.deepcopy(draft)

    # Iterate through each day in the itinerary.
    for day in optimized.get("days", []):

        # Retrieve all stops planned for the current day.
        stops = day.get("stops", [])

        # Optimization only makes sense when there are at least two stops.
        if len(stops) > 1:

            # Reorder stops to reduce travel distance/time.
            # Current implementation may be a mock strategy,
            # but it is structured to support real routing
            # optimization in future sprints.
            reordered_stops = order_stops_by_proximity(stops)

            # Calculate travel time between every consecutive pair of stops.
            for i in range(len(reordered_stops) - 1):

                # Current stop.
                origin = reordered_stops[i]

                # Next stop in the route.
                dest = reordered_stops[i + 1]

                # Estimate travel time (in minutes) between the two stops.
                travel_time = await get_travel_time_minutes(origin, dest)

                # Store the calculated travel time inside the current stop.
                # Example:
                # {
                #     "name": "Egyptian Museum",
                #     "travel_time_to_next_minutes": 15
                # }
                reordered_stops[i]["travel_time_to_next_minutes"] = round(travel_time, 1)

            # Replace the original stop sequence with the optimized sequence.
            day["stops"] = reordered_stops

        # Sum travel times for all stops in this day.
        total_travel = sum(
            s.get("travel_time_to_next_minutes", 0) for s in day.get("stops", [])
        )
        day["total_travel_time_minutes"] = round(total_travel, 1)

    # Save the optimized itinerary into the shared state.
    # This allows downstream agents (budgeting, recommendation,
    # response generation, etc.) to use the optimized version.
    state["optimized_itinerary"] = optimized

    # Return the updated state to the next node in the workflow.
    return state