"""Sync database schema with current SQLAlchemy models.

Revision ID: e930583655d2
Revises: d6499ce70bc5
Create Date: 2026-07-03 21:46:41.268521+00:00

Changes:
- VARCHAR to ENUM: places.category, trip_profiles.budget_level/travel_style/pace
- Add server_default to all timestamp columns (matching model defaults)
- Add comment on messages.card_data
- Drop redundant unique constraints on payments/receipts in favour of
  unique=True on the FK column + unique index
- users.preference_counts: backfill NULLs, add NOT NULL + server_default '{}'

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e930583655d2'
down_revision: Union[str, None] = 'd6499ce70bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'booking_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='booking_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('conversations', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('active', 'archived', 'closed', name='conversation_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('event_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('images', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('images', 'analysis_status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processing_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('itineraries', 'version_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('itineraries', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'archived', name='itinerary_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('itineraries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('itineraries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('itinerary_stops', 'stop_id',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('itinerary_stops', 'order_in_day',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('itinerary_stops', 'status',
               existing_type=postgresql.ENUM('planned', 'visited', 'skipped', 'cancelled', name='stop_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('itinerary_stops', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('messages', 'card_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Structured card data: itinerary_data, hotel_options, flight_options, booking_data',
               existing_nullable=True)
    op.alter_column('messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'completed', 'failed', 'refunded', name='payment_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'paid_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('payments_booking_id_key'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=True)
    op.alter_column('places', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('hotel', 'restaurant', 'attraction', name='place_category'),
               existing_nullable=False,
               postgresql_using='category::place_category')
    op.alter_column('places', 'review_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('receipts', 'issue_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('receipts_payment_id_key'), 'receipts', type_='unique')
    op.drop_index(op.f('ix_receipts_payment_id'), table_name='receipts')
    op.create_index(op.f('ix_receipts_payment_id'), 'receipts', ['payment_id'], unique=True)
    op.alter_column('reviews', 'review_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reviews', 'likes_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('saved_places', 'saved_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('saved_places', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trip_profiles', 'budget_level',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('budget', 'moderate', 'luxury', name='budget_level'),
               existing_nullable=True,
               postgresql_using='budget_level::budget_level')
    op.alter_column('trip_profiles', 'travel_style',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('romantic', 'adventure', 'family', 'business', 'solo', 'cultural', 'relaxation', name='travel_style'),
               existing_nullable=True,
               postgresql_using='travel_style::travel_style')
    op.alter_column('trip_profiles', 'pace',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('packed', 'moderate', 'relaxed', name='trip_pace'),
               existing_nullable=True,
               postgresql_using='pace::trip_pace')
    op.alter_column('trip_profiles', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trip_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trips', 'number_of_travelers',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trips', 'status',
               existing_type=postgresql.ENUM('planning', 'active', 'completed', 'itinerary_draft', 'awaiting_booking', 'booking_pending', 'payment_processing', 'payment_failed', 'booking_confirmed', name='trip_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    # ── Backfill NULL preference_counts before adding NOT NULL ──────────────
    op.execute(
        "UPDATE users SET preference_counts = '{}'::json "
        "WHERE preference_counts IS NULL"
    )
    op.alter_column('users', 'preference_counts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default='{}',
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'preference_counts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trips', 'status',
               existing_type=postgresql.ENUM('planning', 'active', 'completed', 'itinerary_draft', 'awaiting_booking', 'booking_pending', 'payment_processing', 'payment_failed', 'booking_confirmed', name='trip_status'),
               server_default=sa.text("'planning'::trip_status"),
               existing_nullable=False)
    op.alter_column('trips', 'number_of_travelers',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('trip_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trip_profiles', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trip_profiles', 'pace',
               existing_type=sa.Enum('packed', 'moderate', 'relaxed', name='trip_pace'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('trip_profiles', 'travel_style',
               existing_type=sa.Enum('romantic', 'adventure', 'family', 'business', 'solo', 'cultural', 'relaxation', name='travel_style'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('trip_profiles', 'budget_level',
               existing_type=sa.Enum('budget', 'moderate', 'luxury', name='budget_level'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('saved_places', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('saved_places', 'saved_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('reviews', 'likes_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reviews', 'review_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index(op.f('ix_receipts_payment_id'), table_name='receipts')
    op.create_index(op.f('ix_receipts_payment_id'), 'receipts', ['payment_id'], unique=False)
    op.create_unique_constraint(op.f('receipts_payment_id_key'), 'receipts', ['payment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('receipts', 'issue_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('places', 'review_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('places', 'category',
               existing_type=sa.Enum('hotel', 'restaurant', 'attraction', name='place_category'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_unique_constraint(op.f('payments_booking_id_key'), 'payments', ['booking_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('payments', 'paid_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'completed', 'failed', 'refunded', name='payment_status'),
               server_default=sa.text("'pending'::payment_status"),
               existing_nullable=False)
    op.alter_column('messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('messages', 'card_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Structured card data: itinerary_data, hotel_options, flight_options, booking_data',
               existing_nullable=True)
    op.alter_column('itinerary_stops', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('itinerary_stops', 'status',
               existing_type=postgresql.ENUM('planned', 'visited', 'skipped', 'cancelled', name='stop_status'),
               server_default=sa.text("'planned'::stop_status"),
               existing_nullable=False)
    op.alter_column('itinerary_stops', 'order_in_day',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('itinerary_stops', 'stop_id',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("nextval('itinerary_stops_stop_id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('itineraries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('itineraries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('itineraries', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'archived', name='itinerary_status'),
               server_default=sa.text("'draft'::itinerary_status"),
               existing_nullable=False)
    op.alter_column('itineraries', 'version_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('images', 'analysis_status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processing_status'),
               server_default=sa.text("'pending'::processing_status"),
               existing_nullable=False)
    op.alter_column('images', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('event_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('active', 'archived', 'closed', name='conversation_status'),
               server_default=sa.text("'active'::conversation_status"),
               existing_nullable=False)
    op.alter_column('conversations', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='booking_status'),
               server_default=sa.text("'pending'::booking_status"),
               existing_nullable=False)
    op.alter_column('bookings', 'booking_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###
