"""
Route Optimizer — Stage 5 of the multi-agent pipeline.

Deterministic route optimization using OSRM travel times, nearest-neighbor
reordering, and 2-opt local search.
"""

import copy
from ai_engine.graph.state import TripState
from ai_engine.tools.routing_tool import get_reorder_indices, improve_order_2opt, compute_day_matrix, WALK_THRESHOLD_KM
from ai_engine.tools.haversine import haversine


# ── Heavy-field helpers ──────────────────────────────────────────────────────

_HEAVY_STOP_FIELDS = {"photos", "address", "maps_link"}


def _extract_heavy_stop_fields(draft: dict) -> dict[str, dict]:
    """Extract heavy stop fields into an id → {field: value} mapping."""
    heavy = {}
    for day in draft.get("days", []):
        for stop in day.get("stops", []):
            sid = stop.get("id")
            if not sid:
                continue
            payload = {}
            for field in _HEAVY_STOP_FIELDS:
                val = stop.get(field)
                if val:
                    payload[field] = val
            if payload:
                heavy[sid] = payload
    return heavy


def _strip_heavy_stop_fields(day_data: dict) -> None:
    """Remove heavy fields from all stops in *day_data* in-place."""
    for stop in day_data.get("stops", []):
        for field in _HEAVY_STOP_FIELDS:
            stop.pop(field, None)


def _reattach_heavy_stop_fields(optimized: dict, heavy: dict[str, dict]) -> None:
    """Re-attach heavy fields from the original draft back into *optimized*."""
    for day in optimized.get("days", []):
        for stop in day.get("stops", []):
            sid = stop.get("id")
            if sid and sid in heavy:
                for field, val in heavy[sid].items():
                    if field not in stop:
                        stop[field] = val


async def optimize_route(state: TripState) -> TripState:
    """
    Route Optimizer

    Purpose:
    - Takes the draft itinerary generated by the Planning Agent.
    - Creates a deep copy to avoid modifying the original draft.
    - Reorders stops within each day based on geographic proximity.
    - Computes travel times via OSRM with mixed modes:
      walking for nearby pairs (< 2 km), driving for the rest.
    - Tags each stop with a ``transport_mode``.
    - Stores the optimized result in state["optimized_itinerary"].
    """
    draft = state.get("draft_itinerary")
    if not draft or state.get("error"):
        return state

    heavy_fields = _extract_heavy_stop_fields(draft)
    optimized = copy.deepcopy(draft)

    for day in optimized.get("days", []):
        _strip_heavy_stop_fields(day)

    for day in optimized.get("days", []):
        stops = day.get("stops", [])
        if len(stops) > 1:
            matrix = await compute_day_matrix(stops)
            nn_idx = get_reorder_indices(stops, matrix)
            reorder_idx = improve_order_2opt(nn_idx, matrix)
            reordered_stops = [stops[i] for i in reorder_idx]

            # Reassign time-of-day slots by position
            _TIME_SLOTS = ["morning", "afternoon", "evening"]
            for i, stop in enumerate(reordered_stops):
                slot_idx = min(i, len(_TIME_SLOTS) - 1)
                stop["suggested_time_of_day"] = _TIME_SLOTS[slot_idx]

            # Annotate stops with travel times and mode
            for i in range(len(reordered_stops) - 1):
                oi = reorder_idx[i]
                oj = reorder_idx[i + 1]
                dist_km = haversine(
                    reordered_stops[i]["lat"], reordered_stops[i]["lon"],
                    reordered_stops[i + 1]["lat"], reordered_stops[i + 1]["lon"],
                )
                mode = "walking" if dist_km <= WALK_THRESHOLD_KM else "driving"
                reordered_stops[i]["travel_time_to_next_minutes"] = matrix[oi][oj]
                reordered_stops[i]["transport_mode"] = mode

            day["stops"] = reordered_stops

        total_travel = sum(
            s.get("travel_time_to_next_minutes", 0) for s in day.get("stops", [])
        )
        day["total_travel_time_minutes"] = round(total_travel, 1)

    _reattach_heavy_stop_fields(optimized, heavy_fields)
    state["optimized_itinerary"] = optimized

    total_stops = sum(
        len(day.get("stops", [])) for day in optimized.get("days", [])
    )
    total_travel = sum(
        day.get("total_travel_time_minutes", 0)
        for day in optimized.get("days", [])
    )
    state["agent_messages"] = (
        state.get("agent_messages", [])
        + [f"[RouteOptimizer] {len(optimized.get('days', []))} days, "
           f"{total_stops} stops, {total_travel:.0f} min total travel"]
    )
    return state
