"""
Route Optimizer — Stage 5 of the multi-agent pipeline.

Deterministic route optimization using OSRM travel times, nearest-neighbor
reordering, and 2-opt local search.
"""

import copy
from ai_engine.graph.state import TripState
from ai_engine.tools.routing_tool import get_reorder_indices, improve_order_2opt, compute_day_matrix, WALK_THRESHOLD_KM
from ai_engine.tools.haversine import haversine


# ── Heavy-field helpers ──────────────────────────────────────────────────────

_HEAVY_STOP_FIELDS = {"photos", "address", "maps_link"}


def _extract_heavy_stop_fields(draft: dict) -> dict[str, dict]:
    """Extract heavy stop fields into an id → {field: value} mapping."""
    heavy = {}
    for day in draft.get("days", []):
        for stop in day.get("stops", []):
            sid = stop.get("id")
            if not sid:
                continue
            payload = {}
            for field in _HEAVY_STOP_FIELDS:
                val = stop.get(field)
                if val:
                    payload[field] = val
            if payload:
                heavy[sid] = payload
    return heavy


def _strip_heavy_stop_fields(day_data: dict) -> None:
    """Remove heavy fields from all stops in *day_data* in-place."""
    for stop in day_data.get("stops", []):
        for field in _HEAVY_STOP_FIELDS:
            stop.pop(field, None)


def _reattach_heavy_stop_fields(optimized: dict, heavy: dict[str, dict]) -> None:
    """Re-attach heavy fields from the original draft back into *optimized*."""
    for day in optimized.get("days", []):
        for stop in day.get("stops", []):
            sid = stop.get("id")
            if sid and sid in heavy:
                for field, val in heavy[sid].items():
                    if field not in stop:
                        stop[field] = val


async def _optimize_day_stops(stops: list[dict]) -> list[dict]:
    """Reorder stops within a day and annotate travel times."""
    if len(stops) <= 1:
        return stops

    matrix = await compute_day_matrix(stops)

    _TIME_RANK = {"morning": 0, "afternoon": 1, "evening": 2}
    groups: dict[int, list[int]] = {}
    for i, stop in enumerate(stops):
        slot = stop.get("suggested_time_of_day", "")
        rank = _TIME_RANK.get(slot, 3)
        groups.setdefault(rank, []).append(i)

    final_order: list[int] = []
    for rank in sorted(groups.keys()):
        group_indices = groups[rank]
        if len(group_indices) > 1:
            sub_stops = [stops[i] for i in group_indices]
            sub_matrix = [
                [matrix[i][j] for j in group_indices]
                for i in group_indices
            ]
            nn_idx = get_reorder_indices(sub_stops, sub_matrix)
            reorder_idx = improve_order_2opt(nn_idx, sub_matrix)
            final_order.extend([group_indices[i] for i in reorder_idx])
        else:
            final_order.extend(group_indices)

    reordered_stops = [stops[i] for i in final_order]

    for i in range(len(reordered_stops) - 1):
        fi = final_order[i]
        fj = final_order[i + 1]
        dist_km = haversine(
            reordered_stops[i]["lat"], reordered_stops[i]["lon"],
            reordered_stops[i + 1]["lat"], reordered_stops[i + 1]["lon"],
        )
        mode = "walking" if dist_km <= WALK_THRESHOLD_KM else "driving"
        reordered_stops[i]["travel_time_to_next_minutes"] = matrix[fi][fj]
        reordered_stops[i]["transport_mode"] = mode

    if reordered_stops:
        reordered_stops[-1].pop("travel_time_to_next_minutes", None)
        reordered_stops[-1].pop("transport_mode", None)

    return reordered_stops


async def optimize_itinerary_days(
    itinerary: dict,
    day_numbers: list[int] | None = None,
) -> dict:
    """Run OSRM route optimization on specific days (or all days).

    Used after delta edits (ADD / SWAP / REORDER) without rerunning the full
    LangGraph pipeline.
    """
    if not itinerary:
        return itinerary

    heavy_fields = _extract_heavy_stop_fields(itinerary)
    optimized = copy.deepcopy(itinerary)
    target_days = set(day_numbers) if day_numbers else None

    for day in optimized.get("days", []):
        day_num = day.get("day_number")
        if target_days is not None and day_num not in target_days:
            continue

        _strip_heavy_stop_fields(day)
        stops = day.get("stops", [])
        if len(stops) > 1:
            day["stops"] = await _optimize_day_stops(stops)

        total_travel = sum(
            s.get("travel_time_to_next_minutes", 0) for s in day.get("stops", [])
        )
        day["total_travel_time_minutes"] = round(total_travel, 1)

    _reattach_heavy_stop_fields(optimized, heavy_fields)
    return optimized


async def optimize_route(state: TripState) -> TripState:
    """
    Route Optimizer

    Purpose:
    - Takes the draft itinerary generated by the Planning Agent.
    - Creates a deep copy to avoid modifying the original draft.
    - Reorders stops within each day based on geographic proximity.
    - Computes travel times via OSRM with mixed modes:
      walking for nearby pairs (< 2 km), driving for the rest.
    - Tags each stop with a ``transport_mode``.
    - Stores the optimized result in state["optimized_itinerary"].
    """
    draft = state.get("draft_itinerary")
    if not draft or state.get("error"):
        return state

    heavy_fields = _extract_heavy_stop_fields(draft)
    optimized = copy.deepcopy(draft)

    for day in optimized.get("days", []):
        _strip_heavy_stop_fields(day)

    for day in optimized.get("days", []):
        stops = day.get("stops", [])
        if len(stops) > 1:
            day["stops"] = await _optimize_day_stops(stops)

        total_travel = sum(
            s.get("travel_time_to_next_minutes", 0) for s in day.get("stops", [])
        )
        day["total_travel_time_minutes"] = round(total_travel, 1)

    _reattach_heavy_stop_fields(optimized, heavy_fields)
    state["optimized_itinerary"] = optimized

    total_stops = sum(
        len(day.get("stops", [])) for day in optimized.get("days", [])
    )
    total_travel = sum(
        day.get("total_travel_time_minutes", 0)
        for day in optimized.get("days", [])
    )
    state["agent_messages"] = (
        state.get("agent_messages", [])
        + [f"[RouteOptimizer] {len(optimized.get('days', []))} days, "
           f"{total_stops} stops, {total_travel:.0f} min total travel"]
    )
    return state
