// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-azpEy9nkCK8pzBf-MZLF3F9DTRVsm4',
    appId: '1:419367078732:android:b1da2a01c82ccc5aaa5de9',
    messagingSenderId: '419367078732',
    projectId: 'tourmate-ai-62a20',
    storageBucket: 'tourmate-ai-62a20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALKZlNzcZmWzDSi3rTeLUfHQvNwGL2u-U',
    appId: '1:419367078732:ios:efe42a28a7324b18aa5de9',
    messagingSenderId: '419367078732',
    projectId: 'tourmate-ai-62a20',
    storageBucket: 'tourmate-ai-62a20.firebasestorage.app',
    androidClientId: '419367078732-82vm0n8bkp39r74uiic9mdp9fl224l0j.apps.googleusercontent.com',
    iosClientId: '419367078732-0iqtkb7q5jm6vin1ci2pbi4q8voc0l2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourmate',
  );
}
